[package]
name = "fuzzbench"
<<<<<<< HEAD
version = "0.11.2"
=======
version = "0.9.0"
>>>>>>> parent of 416a3b0f (removed fuzzers)
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>", "Dominik Maier <domenukk@gmail.com>"]
edition = "2021"

[features]
default = ["std"]
std = []
<<<<<<< HEAD
no_link_main = ["libafl_targets/libfuzzer_no_link_main"]
=======
>>>>>>> parent of 416a3b0f (removed fuzzers)

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

<<<<<<< HEAD
[profile.release-fuzzbench]
inherits = "release"
debug = false
strip = true

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
which = "4.4"

[dependencies]
libafl = { path = "../../libafl/" }
libafl_bolts = { path = "../../libafl_bolts/" }
=======
[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
which = { version = "4.0.2" }

[dependencies]
libafl = { path = "../../libafl/" }
>>>>>>> parent of 416a3b0f (removed fuzzers)
libafl_targets = { path = "../../libafl_targets/", features = ["sancov_pcguard_hitcounts", "sancov_cmplog", "libfuzzer"] }
# TODO Include it only when building cc
libafl_cc = { path = "../../libafl_cc/" }
clap = { version = "4.0", features = ["default"] }
<<<<<<< HEAD
nix = { version = "0.27", features = ["fs"] }
mimalloc = { version = "*", default-features = false }
env_logger = { version = "*", features = [] }
=======
nix = "0.26"
mimalloc = { version = "*", default-features = false }
>>>>>>> parent of 416a3b0f (removed fuzzers)

[lib]
name = "fuzzbench"
crate-type = ["staticlib"]
